[package]
name = "gpui-hayro"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = "0.2.2"
hayro = "0.4.0"
hayro-interpret = "0.4.0"
hayro-svg = "0.2.0"
log = "0.4.29"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
